# -*- coding: utf-8 -*-
"""re_adv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-BNqCk5prDAF2rbTC3eugOJUsf5zksh
"""

# ============================================================
# BILLBOARD DETECTOR — PART 1: SETUP & DATASET PREPARATION
# Run this cell-by-cell in Google Colab
# ============================================================

# ── CELL 1: Install & verify environment ────────────────────
!pip install -q ultralytics supervision

import os, cv2, torch, yaml, zipfile, shutil, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from pathlib import Path
from google.colab import files, drive

print(f"PyTorch  : {torch.__version__}")
print(f"CUDA     : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU      : {torch.cuda.get_device_name(0)}")
    print(f"VRAM     : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("⚠️  No GPU detected. Go to Runtime → Change runtime type → T4 GPU")

# ── CELL 2: Mount Google Drive (CRITICAL — saves your work) ─
drive.mount('/content/drive')
DRIVE_SAVE_DIR = "/content/drive/MyDrive/billboard_project"
os.makedirs(DRIVE_SAVE_DIR, exist_ok=True)
print(f"✅ Drive mounted. All outputs → {DRIVE_SAVE_DIR}")

# ── CELL 3: Upload your dataset zip ─────────────────────────
print("Upload your dataset .zip file:")
uploaded = files.upload()

zip_path = next((f for f in uploaded if f.endswith('.zip')), None)
if zip_path is None:
    raise FileNotFoundError("❌ No .zip file found. Please upload your dataset zip.")

print(f"✅ Received: {zip_path}")

# ── CELL 4: Extract and inspect ─────────────────────────────
RAW  = "datasets/raw"
OUT  = "datasets/billboard"

!rm -rf datasets && mkdir -p datasets
with zipfile.ZipFile(zip_path, 'r') as zf:
    zf.extractall(RAW)

print("\n📁 Extracted structure (first 30 files):")
!find datasets/raw -type f | head -30

# ── CELL 5: Auto-locate images & annotations folders ────────
img_dir = None
ann_dir = None

for root, dirs, _ in os.walk(RAW):
    for d in dirs:
        full = os.path.join(root, d)
        if d == "images" and img_dir is None:
            img_dir = full
        elif d in ("annotations", "labels", "csvs") and ann_dir is None:
            ann_dir = full

# Fallback: scan for CSVs anywhere
if ann_dir is None:
    for root, dirs, files_list in os.walk(RAW):
        csvs = [f for f in files_list if f.endswith('.csv')]
        if csvs:
            ann_dir = root
            break

if img_dir is None or ann_dir is None:
    print("❌ Could not auto-find folders. Listing raw structure:")
    !find datasets/raw -type d
    raise FileNotFoundError(
        "Set img_dir and ann_dir manually above after inspecting the structure."
    )

print(f"✅ Images      : {img_dir}  ({len(os.listdir(img_dir))} files)")
print(f"✅ Annotations : {ann_dir}  ({len(os.listdir(ann_dir))} files)")

# ── CELL 6: Inspect one annotation CSV ──────────────────────
csv_files = sorted([f for f in os.listdir(ann_dir) if f.endswith('.csv')])
print(f"\nTotal annotation CSVs: {len(csv_files)}")
print("\nSample CSV columns:")
sample_df = pd.read_csv(os.path.join(ann_dir, csv_files[0]))
print(sample_df.head())
print(f"\nColumns: {list(sample_df.columns)}")
print(f"Labels found in sample: {sample_df['label'].unique()}")

# ── CELL 7: Build class map & verify coordinate format ──────
all_labels = set()
coord_stats = {'max_x': 0, 'max_y': 0, 'min_x': 9999, 'min_y': 9999}

for cf in csv_files:
    df = pd.read_csv(os.path.join(ann_dir, cf))
    all_labels.update(df['label'].unique())
    # Detect if coords are normalized (0-1) or pixel values
    for col in ['x1', 'x2']:
        if col in df.columns:
            coord_stats['max_x'] = max(coord_stats['max_x'], df[col].max())
            coord_stats['min_x'] = min(coord_stats['min_x'], df[col].min())
    for col in ['y1', 'y2']:
        if col in df.columns:
            coord_stats['max_y'] = max(coord_stats['max_y'], df[col].max())
            coord_stats['min_y'] = min(coord_stats['min_y'], df[col].min())

class_names = sorted(all_labels)
class_to_id = {name: i for i, name in enumerate(class_names)}

IS_NORMALIZED = (coord_stats['max_x'] <= 1.0 and coord_stats['max_y'] <= 1.0)
print(f"\nClasses ({len(class_names)}): {class_names}")
print(f"Coordinate range — X: [{coord_stats['min_x']:.3f}, {coord_stats['max_x']:.3f}]")
print(f"Coordinate range — Y: [{coord_stats['min_y']:.3f}, {coord_stats['max_y']:.3f}]")
print(f"Coords already normalized: {IS_NORMALIZED}")
# If IS_NORMALIZED=False → pixel coords (need image W/H to normalize)
# We handle both cases in the next cell

# ── CELL 8: Match image ↔ annotation pairs ──────────────────
VALID_EXT = ['.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG']

base_names = []
unmatched = []
for cf in csv_files:
    stem = os.path.splitext(cf)[0]
    found = False
    for ext in VALID_EXT:
        img_path = os.path.join(img_dir, stem + ext)
        if os.path.exists(img_path):
            base_names.append((stem, ext))
            found = True
            break
    if not found:
        unmatched.append(stem)

print(f"\n✅ Matched pairs      : {len(base_names)}")
print(f"⚠️  Unmatched CSVs    : {len(unmatched)}")
if unmatched[:5]:
    print(f"   Samples           : {unmatched[:5]}")

if len(base_names) == 0:
    raise ValueError("No matched image-annotation pairs found. Check folder structure.")

# ── CELL 9: Convert to YOLO format with normalization ───────
random.seed(42)
random.shuffle(base_names)

n       = len(base_names)
n_train = int(n * 0.80)
n_val   = int(n * 0.10)
# remaining 10% → test

splits = {
    'train': base_names[:n_train],
    'val'  : base_names[n_train : n_train + n_val],
    'test' : base_names[n_train + n_val :],
}

skipped = 0
for split_name, items in splits.items():
    os.makedirs(f"{OUT}/{split_name}/images", exist_ok=True)
    os.makedirs(f"{OUT}/{split_name}/labels", exist_ok=True)

    for stem, ext in items:
        src_img = os.path.join(img_dir, stem + ext)
        dst_img = os.path.join(OUT, split_name, "images", stem + ext)
        dst_lbl = os.path.join(OUT, split_name, "labels", stem + ".txt")

        # Read image dimensions for normalization
        img = cv2.imread(src_img)
        if img is None:
            skipped += 1
            continue
        H, W = img.shape[:2]

        df = pd.read_csv(os.path.join(ann_dir, stem + '.csv'))
        lines = []
        for _, row in df.iterrows():
            x1, y1 = float(row['x1']), float(row['y1'])
            x2, y2 = float(row['x2']), float(row['y2'])

            # Normalize if pixel coords
            if not IS_NORMALIZED:
                x1, x2 = x1 / W, x2 / W
                y1, y2 = y1 / H, y2 / H

            # Clamp to [0, 1]
            x1 = max(0.0, min(1.0, x1))
            x2 = max(0.0, min(1.0, x2))
            y1 = max(0.0, min(1.0, y1))
            y2 = max(0.0, min(1.0, y2))

            cx = (x1 + x2) / 2
            cy = (y1 + y2) / 2
            bw = abs(x2 - x1)
            bh = abs(y2 - y1)

            # Skip degenerate boxes
            if bw < 0.005 or bh < 0.005:
                continue

            cid = class_to_id[row['label']]
            lines.append(f"{cid} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")

        if lines:
            shutil.copy2(src_img, dst_img)
            with open(dst_lbl, 'w') as f:
                f.write('\n'.join(lines) + '\n')
        else:
            skipped += 1  # empty annotation

    print(f"  {split_name:6s}: {len(items)} images")

print(f"\n⚠️  Skipped (bad/empty): {skipped}")

# ── CELL 10: Write data.yaml ─────────────────────────────────
data_yaml = {
    'path'  : os.path.abspath(OUT),
    'train' : 'train/images',
    'val'   : 'val/images',
    'test'  : 'test/images',
    'nc'    : len(class_names),
    'names' : class_names,
}
yaml_path = f"{OUT}/data.yaml"
with open(yaml_path, 'w') as f:
    yaml.dump(data_yaml, f, default_flow_style=False)

print(f"\n✅ data.yaml saved → {yaml_path}")
print(yaml.dump(data_yaml))

# ── CELL 11: Visualize samples with ground-truth boxes ───────
def show_yolo_samples(split='train', n_samples=6):
    img_folder = f"{OUT}/{split}/images"
    lbl_folder = f"{OUT}/{split}/labels"
    imgs = [f for f in os.listdir(img_folder) if f.lower().endswith(('.jpg','.jpeg','.png'))]
    random.shuffle(imgs)
    imgs = imgs[:n_samples]

    cols = 3
    rows = (len(imgs) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(18, 6 * rows))
    axes = np.array(axes).flatten()

    colors = plt.cm.get_cmap('tab10', len(class_names))

    for ax, fname in zip(axes, imgs):
        img_path = os.path.join(img_folder, fname)
        lbl_path = os.path.join(lbl_folder, os.path.splitext(fname)[0] + '.txt')

        img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        H, W = img.shape[:2]
        ax.imshow(img)

        if os.path.exists(lbl_path):
            with open(lbl_path) as f:
                for line in f:
                    parts = line.strip().split()
                    if len(parts) != 5:
                        continue
                    cid, cx, cy, bw, bh = int(parts[0]), *map(float, parts[1:])
                    x1 = (cx - bw / 2) * W
                    y1 = (cy - bh / 2) * H
                    rect = patches.Rectangle(
                        (x1, y1), bw * W, bh * H,
                        linewidth=2, edgecolor=colors(cid), facecolor='none'
                    )
                    ax.add_patch(rect)
                    ax.text(x1, y1 - 4, class_names[cid], color=colors(cid),
                            fontsize=9, weight='bold',
                            bbox=dict(fc='white', alpha=0.5, pad=1))
        ax.axis('off')
        ax.set_title(fname[:30], fontsize=8)

    for ax in axes[len(imgs):]:
        ax.axis('off')

    plt.suptitle(f"Ground Truth — {split} split", fontsize=14, weight='bold')
    plt.tight_layout()
    plt.savefig(f"/content/drive/MyDrive/billboard_project/gt_samples_{split}.png", dpi=120)
    plt.show()
    print(f"✅ Saved to Drive")

show_yolo_samples('train', n_samples=6)

print("\n✅ PART 1 COMPLETE — Dataset is ready.")
print(f"   Train : {len(splits['train'])} images")
print(f"   Val   : {len(splits['val'])} images")
print(f"   Test  : {len(splits['test'])} images")
print(f"\n▶  Now open Part 2 notebook for training.")

# ============================================================
# BILLBOARD DETECTOR — PART 2 (FIXED): TRAINING
# Fix: handles Ultralytics ≥8.4 which saves to runs/detect/runs/train/
# ============================================================

# ── CELL 1: Reinstall & reload ───────────────────────────────
!pip install -q ultralytics

import os, yaml, glob, shutil, torch
import matplotlib.pyplot as plt
from ultralytics import YOLO
from google.colab import drive

drive.mount('/content/drive')

OUT      = "datasets/billboard"
YAML     = f"{OUT}/data.yaml"
DRIVE_DIR = "/content/drive/MyDrive/billboard_project"
os.makedirs(DRIVE_DIR, exist_ok=True)

# ── CELL 2: Verify dataset ────────────────────────────────────
if not os.path.exists(YAML):
    raise FileNotFoundError("❌ data.yaml not found — run Part 1 first.")

with open(YAML) as f:
    cfg = yaml.safe_load(f)

print(f"✅ Dataset loaded — Classes: {cfg['names']}")
for split in ['train', 'val', 'test']:
    img_dir = os.path.join(cfg['path'], split, 'images')
    n = len(os.listdir(img_dir)) if os.path.exists(img_dir) else 0
    print(f"   {split:6s}: {n} images")

# ── CELL 3: Auto-select model size ───────────────────────────
n_train = len(os.listdir(os.path.join(cfg['path'], 'train', 'images')))

if n_train < 500:
    MODEL_SIZE, BATCH = "yolov8s.pt", 16
elif n_train < 2000:
    MODEL_SIZE, BATCH = "yolov8m.pt", 12
else:
    MODEL_SIZE, BATCH = "yolov8l.pt", 8

print(f"\n📊 Train size: {n_train}  →  model={MODEL_SIZE}  batch={BATCH}")
model = YOLO(MODEL_SIZE)

# ── CELL 4: Train ────────────────────────────────────────────
results = model.train(
    data          = YAML,
    epochs        = 200,
    imgsz         = 640,
    batch         = BATCH,
    lr0           = 0.005,
    lrf           = 0.01,
    cos_lr        = True,
    warmup_epochs = 5,
    warmup_bias_lr= 0.1,
    warmup_momentum=0.8,
    weight_decay  = 0.0005,
    optimizer     = "AdamW",
    momentum      = 0.937,
    box           = 7.5,
    cls           = 0.5,
    dfl           = 1.5,
    hsv_h         = 0.015,
    hsv_s         = 0.7,
    hsv_v         = 0.4,
    degrees       = 10.0,
    translate     = 0.1,
    scale         = 0.6,
    shear         = 5.0,
    perspective   = 0.0005,
    flipud        = 0.0,
    fliplr        = 0.5,
    mosaic        = 1.0,
    mixup         = 0.1,
    copy_paste    = 0.0,
    close_mosaic  = 20,
    iou           = 0.6,
    patience      = 40,
    project       = "runs/train",
    name          = "billboard_v1",
    exist_ok      = False,
    seed          = 42,
    verbose       = True,
    save          = True,
    save_period   = 10,
    plots         = True,
    overlap_mask  = True,
    val           = True,
    cache         = False,
)

print("\n✅ Training complete!")

# ── CELL 5: Robust weight finder (fixes the path bug) ─────────
# Ultralytics ≥8.4 may prefix with 'detect/' depending on task.
# We search the entire /content tree for best.pt under any
# billboard_v1* folder so version differences don't matter.

def find_run_dir(name="billboard_v1"):
    """Search all possible Ultralytics output locations."""
    patterns = [
        f"/content/runs/train/{name}*/weights/best.pt",
        f"/content/runs/detect/runs/train/{name}*/weights/best.pt",
        f"/content/runs/detect/{name}*/weights/best.pt",
        f"/content/**/weights/best.pt",          # wildcard fallback
    ]
    for pat in patterns:
        hits = sorted(glob.glob(pat, recursive=True))
        if hits:
            best_pt  = hits[-1]
            run_dir  = os.path.dirname(os.path.dirname(best_pt))  # strip /weights/best.pt
            print(f"✅ Found best.pt : {best_pt}")
            print(f"   Run dir       : {run_dir}")
            return run_dir, best_pt
    return None, None

run_dir, best_pt = find_run_dir("billboard_v1")

if best_pt is None:
    # Last-resort: use the path YOLO reported directly
    if hasattr(results, 'save_dir'):
        run_dir  = str(results.save_dir)
        best_pt  = os.path.join(run_dir, "weights", "best.pt")
        print(f"✅ Using results.save_dir: {run_dir}")
    else:
        print("❌ Could not locate weights. Listing /content/runs:")
        !find /content/runs -name "*.pt" 2>/dev/null
        raise FileNotFoundError("Cannot find best.pt. See listing above.")

# ── CELL 6: Copy to Drive immediately ────────────────────────
last_pt = os.path.join(run_dir, "weights", "last.pt")

shutil.copy2(best_pt, os.path.join(DRIVE_DIR, "best.pt"))
print(f"✅ best.pt  → Drive")

if os.path.exists(last_pt):
    shutil.copy2(last_pt, os.path.join(DRIVE_DIR, "last.pt"))
    print(f"✅ last.pt  → Drive")

# Also save the run dir path for Part 3
with open(os.path.join(DRIVE_DIR, "run_dir.txt"), "w") as f:
    f.write(run_dir)
print(f"✅ run_dir.txt saved → {DRIVE_DIR}/run_dir.txt")

# ── CELL 7: Training curves ───────────────────────────────────
def show_training_curves(run_dir):
    import pandas as pd
    csv_path = os.path.join(run_dir, "results.csv")
    if not os.path.exists(csv_path):
        print(f"⚠️  results.csv not found at {csv_path}")
        return

    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()
    print(f"\nColumns in results.csv: {list(df.columns)}")

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    loss_pairs = [
        ('train/box_loss', 'val/box_loss',  'Box Loss'),
        ('train/cls_loss', 'val/cls_loss',  'Class Loss'),
        ('train/dfl_loss', 'val/dfl_loss',  'DFL Loss'),
    ]
    metric_cols = [
        ('metrics/mAP50(B)',     'mAP@0.5'),
        ('metrics/mAP50-95(B)', 'mAP@0.5:0.95'),
        ('metrics/precision(B)','Precision'),
    ]

    for ax, (tr, va, title) in zip(axes[0], loss_pairs):
        if tr in df.columns:
            ax.plot(df[tr], label='train', color='royalblue')
        if va in df.columns:
            ax.plot(df[va], label='val',   color='tomato')
        ax.set_title(title); ax.set_xlabel('Epoch')
        ax.legend(); ax.grid(True, alpha=0.3)

    for ax, (col, title) in zip(axes[1], metric_cols):
        if col in df.columns:
            ax.plot(df[col], color='seagreen')
            if col == 'metrics/mAP50(B)':
                best_ep = df[col].idxmax()
                ax.axvline(best_ep, color='red', linestyle='--', alpha=0.7,
                           label=f'Best: {df[col].max():.4f} @ep{best_ep}')
                ax.legend()
        ax.set_title(title); ax.set_xlabel('Epoch')
        ax.grid(True, alpha=0.3)

    plt.suptitle("Billboard Detector — Training Curves", fontsize=14, weight='bold')
    plt.tight_layout()
    out_path = os.path.join(DRIVE_DIR, "training_curves.png")
    plt.savefig(out_path, dpi=120, bbox_inches='tight')
    plt.show()
    print(f"✅ Curves saved → {out_path}")

    print(f"\n📊 Best metrics:")
    for col in ['metrics/mAP50(B)', 'metrics/mAP50-95(B)',
                'metrics/precision(B)', 'metrics/recall(B)']:
        if col in df.columns:
            print(f"   {col:35s} = {df[col].max():.4f}")

show_training_curves(run_dir)

# ── CELL 8: Copy full run folder to Drive ────────────────────
dst = os.path.join(DRIVE_DIR, "run_v1")
if os.path.exists(dst):
    shutil.rmtree(dst)
shutil.copytree(run_dir, dst)
print(f"✅ Full run → {dst}")

print("\n✅ PART 2 COMPLETE — open Part 3 for evaluation.")

# ============================================================
# BILLBOARD DETECTOR — PART 3 (FIXED): EVALUATION & TESTING
# Fix: reads run_dir.txt saved by Part 2 — no more path guessing
# ============================================================

# ── CELL 1: Setup ────────────────────────────────────────────
!pip install -q ultralytics

import os, cv2, glob, random, yaml, shutil
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from ultralytics import YOLO
from google.colab import drive, files as colab_files

drive.mount('/content/drive')

OUT       = "datasets/billboard"
YAML      = f"{OUT}/data.yaml"
DRIVE_DIR = "/content/drive/MyDrive/billboard_project"

# ── CELL 2: Load best.pt (robust — 3-tier fallback) ──────────
best_pt = None

# Tier 1: run_dir.txt written by fixed Part 2 (most reliable)
run_dir_file = os.path.join(DRIVE_DIR, "run_dir.txt")
if os.path.exists(run_dir_file):
    with open(run_dir_file) as f:
        saved_run_dir = f.read().strip()
    candidate = os.path.join(saved_run_dir, "weights", "best.pt")
    if os.path.exists(candidate):
        best_pt = candidate
        run_dir = saved_run_dir
        print(f"✅ [Tier 1] Loaded from saved run_dir: {best_pt}")

# Tier 2: full filesystem search (catches any Ultralytics path variant)
if best_pt is None:
    patterns = [
        "/content/runs/train/billboard_v1*/weights/best.pt",
        "/content/runs/detect/runs/train/billboard_v1*/weights/best.pt",
        "/content/runs/detect/billboard_v1*/weights/best.pt",
        "/content/**/billboard_v1*/weights/best.pt",
    ]
    for pat in patterns:
        hits = sorted(glob.glob(pat, recursive=True))
        if hits:
            best_pt = hits[-1]
            run_dir = os.path.dirname(os.path.dirname(best_pt))
            print(f"✅ [Tier 2] Found by glob: {best_pt}")
            break

# Tier 3: copy from Drive (new session after training)
if best_pt is None:
    drive_best = os.path.join(DRIVE_DIR, "best.pt")
    if os.path.exists(drive_best):
        os.makedirs("/content/eval_weights", exist_ok=True)
        shutil.copy2(drive_best, "/content/eval_weights/best.pt")
        best_pt = "/content/eval_weights/best.pt"
        # Try to find run_dir from Drive
        drive_run = os.path.join(DRIVE_DIR, "run_v1")
        run_dir   = drive_run if os.path.exists(drive_run) else None
        print(f"✅ [Tier 3] Loaded from Drive: {best_pt}")

if best_pt is None:
    print("❌ best.pt not found anywhere. Debug info:")
    !find /content -name "best.pt" 2>/dev/null
    !find /content/drive/MyDrive/billboard_project -type f 2>/dev/null
    raise FileNotFoundError("Run Part 2 (fixed) first.")

model = YOLO(best_pt)
class_names = list(model.names.values())
print(f"\n✅ Model loaded — Classes: {class_names}")

# ── CELL 3: Rebuild dataset if needed (new session) ───────────
# If YAML doesn't exist (session reset after training), we need
# to rebuild just enough to run validation.
if not os.path.exists(YAML):
    print("⚠️  Dataset not found locally. Run Part 1 to rebuild it.")
    print("   Skipping dataset-dependent cells.")
    DATASET_AVAILABLE = False
else:
    DATASET_AVAILABLE = True
    print(f"✅ Dataset found at {OUT}")

# ── CELL 4: Validate on val split (best.pt) ───────────────────
if DATASET_AVAILABLE:
    print("\n📊 Validating on val split using best.pt ...")
    val_metrics = model.val(
        data    = YAML,
        split   = 'val',
        conf    = 0.001,
        iou     = 0.6,
        imgsz   = 640,
        verbose = True,
    )
    print(f"\n{'═'*45}")
    print(f"  VAL  mAP@0.5        : {val_metrics.box.map50:.4f}")
    print(f"  VAL  mAP@0.5:0.95   : {val_metrics.box.map:.4f}")
    print(f"  VAL  Precision      : {val_metrics.box.mp:.4f}")
    print(f"  VAL  Recall         : {val_metrics.box.mr:.4f}")
    print(f"{'═'*45}")
    if len(class_names) > 1:
        print("\nPer-class mAP@0.5:")
        for i, name in enumerate(class_names):
            print(f"  {name:20s}: {val_metrics.box.maps[i]:.4f}")

# ── CELL 5: Test split evaluation ────────────────────────────
if DATASET_AVAILABLE:
    print("\n📊 Evaluating on test split ...")
    test_metrics = model.val(
        data    = YAML,
        split   = 'test',
        conf    = 0.001,
        iou     = 0.6,
        imgsz   = 640,
        verbose = False,
    )
    print(f"\n{'═'*45}")
    print(f"  TEST mAP@0.5        : {test_metrics.box.map50:.4f}")
    print(f"  TEST mAP@0.5:0.95   : {test_metrics.box.map:.4f}")
    print(f"  TEST Precision      : {test_metrics.box.mp:.4f}")
    print(f"  TEST Recall         : {test_metrics.box.mr:.4f}")
    print(f"{'═'*45}")

# ── CELL 6: Qualitative visualisation ────────────────────────
def visualize_predictions(img_dir, n=9, conf=0.25, iou=0.5, title="Predictions"):
    imgs = [f for f in os.listdir(img_dir)
            if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    random.shuffle(imgs)
    imgs = imgs[:n]

    cols = 3
    rows = (len(imgs) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(18, 6 * rows))
    axes = np.array(axes).flatten()

    for ax, fname in zip(axes, imgs):
        img_path = os.path.join(img_dir, fname)
        res = model(img_path, conf=conf, iou=iou, verbose=False)[0]
        ann = res.plot(line_width=2, font_size=10)
        ax.imshow(cv2.cvtColor(ann, cv2.COLOR_BGR2RGB))
        ax.axis('off')
        ax.set_title(f"{fname[:25]} — {len(res.boxes)} det", fontsize=8)

    for ax in axes[len(imgs):]:
        ax.axis('off')

    plt.suptitle(title, fontsize=14, weight='bold')
    plt.tight_layout()
    save_path = os.path.join(DRIVE_DIR, f"{title.replace(' ','_')}.png")
    plt.savefig(save_path, dpi=120, bbox_inches='tight')
    plt.show()
    print(f"✅ Saved: {save_path}")

if DATASET_AVAILABLE and os.path.exists(f"{OUT}/test/images"):
    visualize_predictions(f"{OUT}/test/images", n=9, title="Test_Set_Predictions")

# ── CELL 7: Robust corner detection ───────────────────────────
def order_corners(pts):
    pts  = pts.reshape(4, 2).astype(np.float32)
    rect = np.zeros((4, 2), dtype=np.float32)
    s    = pts.sum(axis=1)
    d    = np.diff(pts, axis=1).flatten()
    rect[0] = pts[np.argmin(s)]   # TL
    rect[2] = pts[np.argmax(s)]   # BR
    rect[1] = pts[np.argmin(d)]   # TR
    rect[3] = pts[np.argmax(d)]   # BL
    return rect

def get_billboard_corners(img_path, model, conf=0.25,
                          canny_lo=30, canny_hi=100, poly_eps=0.03):
    img = cv2.imread(img_path)
    if img is None:
        return [], None
    H, W   = img.shape[:2]
    results = model(img_path, conf=conf, verbose=False)[0]
    detections = []

    for box, conf_score in zip(
        results.boxes.xyxy.cpu().numpy(),
        results.boxes.conf.cpu().numpy()
    ):
        x1, y1, x2, y2 = box.astype(int)
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(W, x2), min(H, y2)
        roi = img[y1:y2, x1:x2]
        if roi.size == 0:
            continue

        gray   = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
        blur   = cv2.GaussianBlur(gray, (5, 5), 0)
        edges  = cv2.Canny(blur, canny_lo, canny_hi)
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
        edges  = cv2.dilate(edges, kernel, iterations=1)

        contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
        corners, method = None, 'bbox_fallback'

        if contours:
            contours = sorted(contours, key=cv2.contourArea, reverse=True)
            for cnt in contours[:3]:
                peri   = cv2.arcLength(cnt, True)
                approx = cv2.approxPolyDP(cnt, poly_eps * peri, True)
                if len(approx) == 4:
                    roi_h, roi_w = roi.shape[:2]
                    if cv2.contourArea(approx) / (roi_w * roi_h + 1e-6) > 0.1:
                        pts     = approx.reshape(4, 2) + np.array([x1, y1])
                        corners = order_corners(pts)
                        method  = 'contour'
                        break

        if corners is None:
            corners = order_corners(np.array(
                [[x1,y1],[x2,y1],[x2,y2],[x1,y2]], dtype=np.float32))

        detections.append({
            'bbox'   : (x1, y1, x2, y2),
            'corners': corners,
            'method' : method,
            'conf'   : float(conf_score),
        })

    return detections, img

def visualize_corners(img_path, model, conf=0.25):
    detections, img = get_billboard_corners(img_path, model, conf=conf)
    if img is None:
        print(f"❌ Cannot read {img_path}")
        return []

    vis = img.copy()
    corner_colors = [(0,255,0),(255,0,0),(0,0,255),(255,165,0)]
    labels        = ['TL','TR','BR','BL']

    for det in detections:
        x1, y1, x2, y2 = det['bbox']
        corners = det['corners'].astype(int)
        color   = (0,200,255) if det['method'] == 'contour' else (100,100,255)
        cv2.rectangle(vis, (x1,y1), (x2,y2), color, 2)
        for i in range(4):
            cv2.line(vis, tuple(corners[i]), tuple(corners[(i+1)%4]), (0,255,0), 2)
        for pt, col, lbl in zip(corners, corner_colors, labels):
            cv2.circle(vis, tuple(pt), 8, col, -1)
            cv2.putText(vis, lbl, (pt[0]+5, pt[1]-5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, col, 2)
        cv2.putText(vis, f"conf:{det['conf']:.2f} [{det['method']}]",
                    (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,0), 1)

    plt.figure(figsize=(12, 8))
    plt.imshow(cv2.cvtColor(vis, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"Corners — {os.path.basename(img_path)}")
    plt.tight_layout()
    plt.show()

    print(f"Found {len(detections)} billboard(s):")
    for i, det in enumerate(detections):
        print(f"  [{i}] conf={det['conf']:.3f}  method={det['method']}")
        for lbl, pt in zip(labels, det['corners']):
            print(f"       {lbl}: ({pt[0]:.0f}, {pt[1]:.0f})")

    return detections

# ── CELL 8: Upload & test your own images ────────────────────
print("\nUpload test images (jpg/png):")
uploaded = colab_files.upload()

VALID_EXT = ('.jpg', '.jpeg', '.png')
for fname in uploaded:
    if not fname.lower().endswith(VALID_EXT):
        continue
    print(f"\n{'─'*50}")
    print(f"Processing: {fname}")
    visualize_corners(fname, model, conf=0.25)

# ── CELL 9: Confidence threshold sweep ───────────────────────
def threshold_sweep(img_path, model, thresholds=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6]):
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    axes = axes.flatten()
    for ax, conf in zip(axes, thresholds):
        res = model(img_path, conf=conf, verbose=False)[0]
        ann = res.plot(line_width=2)
        ax.imshow(cv2.cvtColor(ann, cv2.COLOR_BGR2RGB))
        ax.axis('off')
        ax.set_title(f"conf={conf:.1f}  →  {len(res.boxes)} det", fontsize=11)
    plt.suptitle(f"Confidence Sweep — {os.path.basename(img_path)}",
                 fontsize=13, weight='bold')
    plt.tight_layout()
    out = os.path.join(DRIVE_DIR, f"conf_sweep_{os.path.basename(img_path)}.png")
    plt.savefig(out, dpi=100)
    plt.show()
    print(f"✅ Saved: {out}")

valid_uploads = [f for f in uploaded if f.lower().endswith(VALID_EXT)]
if valid_uploads:
    threshold_sweep(valid_uploads[0], model)

# ── CELL 10: Download best.pt ────────────────────────────────
print("\nDownloading best.pt ...")
colab_files.download(best_pt)
print("✅ PART 3 COMPLETE")

# Commented out IPython magic to ensure Python compatibility.
"""
Part 4: Custom Advertisement Replacement in Detected Bounding Boxes
====================================================================
Run this AFTER Part 2 (training) and Part 3 (evaluation) are complete.

What this does:
- Loads your trained YOLOv8 model (best.pt)
- Detects billboards/signage in images or video frames
- Warps a custom advertisement image into each detected bounding box
  with perspective-correct homography (OpenCV)
- Supports:
    • Single image replacement
    • Batch folder processing
    • Video frame-by-frame replacement
    • Optional blending / alpha compositing for realism

Usage (in Colab cell):
#     %run part4_ad_replacement.py
Or import and call functions directly.
"""

# ── Imports ─────────────────────────────────────────────────────────────────
import cv2
import numpy as np
from pathlib import Path
import shutil
import glob
import os

# ── Google Drive Mount ───────────────────────────────────────────────────────
try:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)
    DRIVE_ROOT = Path("/content/drive/MyDrive/billboard_project")
    print("✅ Google Drive mounted.")
except Exception:
    DRIVE_ROOT = Path("billboard_project")
    print("⚠️  Not in Colab – using local billboard_project/ folder.")

# ── Paths ────────────────────────────────────────────────────────────────────
AD_OUTPUT_DIR   = DRIVE_ROOT / "ad_replaced_output"
AD_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CUSTOM_AD_PATH  = DRIVE_ROOT / "custom_ad.jpg"   # ← put your ad image here
MODEL_PATH      = DRIVE_ROOT / "best.pt"          # trained model from Part 2

# ── Locate Model ─────────────────────────────────────────────────────────────
def find_model() -> Path:
    """Try multiple locations to find best.pt"""
    candidates = [
        MODEL_PATH,
        DRIVE_ROOT / "runs" / "detect" / "train" / "weights" / "best.pt",
        *[Path(p) for p in glob.glob(str(DRIVE_ROOT / "**" / "best.pt"), recursive=True)],
        Path("runs/detect/train/weights/best.pt"),
    ]
    for p in candidates:
        if p.exists():
            print(f"✅ Model found: {p}")
            return p
    raise FileNotFoundError(
        "❌ best.pt not found. Make sure Part 2 training finished and "
        "best.pt was saved to Drive."
    )

# ── Load YOLO Model ──────────────────────────────────────────────────────────
def load_model(conf_threshold: float = 0.25):
    from ultralytics import YOLO
    model_path = find_model()
    model = YOLO(str(model_path))
    model.conf = conf_threshold
    print(f"✅ YOLOv8 model loaded (conf ≥ {conf_threshold})")
    return model

# ── Ad Image Loader / Creator ────────────────────────────────────────────────
def load_or_create_ad(ad_path: Path) -> np.ndarray:
    """
    Load the custom advertisement image.
    If none exists, generate a vivid placeholder so the pipeline still runs.
    """
    if ad_path.exists():
        ad = cv2.imread(str(ad_path))
        if ad is not None:
            print(f"✅ Custom ad loaded: {ad_path}  ({ad.shape[1]}×{ad.shape[0]})")
            return ad

    print("⚠️  No custom_ad.jpg found – generating a placeholder ad.")
    ad = np.zeros((300, 600, 3), dtype=np.uint8)

    # Gradient background
    for y in range(300):
        r = int(20  + (235 * y / 300))
        g = int(10  + (100 * y / 300))
        b = int(200 - (180 * y / 300))
        ad[y, :] = (b, g, r)

    # White border
    cv2.rectangle(ad, (4, 4), (595, 295), (255, 255, 255), 3)

    # Text
    font = cv2.FONT_HERSHEY_DUPLEX
    cv2.putText(ad, "YOUR AD HERE",   (80,  130), font, 2.0,  (255, 255, 255), 3, cv2.LINE_AA)
    cv2.putText(ad, "billboard_project", (120, 185), font, 0.9,  (220, 220, 255), 2, cv2.LINE_AA)
    cv2.putText(ad, "Replace custom_ad.jpg on Drive", (55, 240), font, 0.65, (180, 220, 255), 1, cv2.LINE_AA)

    # Save placeholder to Drive for reference
    cv2.imwrite(str(ad_path), ad)
    print(f"   Placeholder saved → {ad_path}")
    return ad


# ── Core: Warp Ad into Bounding Box ─────────────────────────────────────────
def warp_ad_into_bbox(
    frame: np.ndarray,
    ad_img: np.ndarray,
    x1: int, y1: int, x2: int, y2: int,
    blend_alpha: float = 0.88,
    edge_fade: bool = True,
) -> np.ndarray:
    """
    Warp `ad_img` into the axis-aligned bounding box [x1,y1,x2,y2] on `frame`.

    Parameters
    ----------
    blend_alpha : 0.0–1.0  — 1.0 = fully replace, lower = ghosted blend
    edge_fade   : feather edges for a more natural look
    """
    frame = frame.copy()
    bw, bh = x2 - x1, y2 - y1
    if bw < 10 or bh < 10:
        return frame

    # ── Four corners of the destination bounding box ──────────────────────
    dst_pts = np.array([
        [x1, y1],
        [x2, y1],
        [x2, y2],
        [x1, y2],
    ], dtype=np.float32)

    # ── Four corners of the source ad image ───────────────────────────────
    ah, aw = ad_img.shape[:2]
    src_pts = np.array([
        [0,  0 ],
        [aw, 0 ],
        [aw, ah],
        [0,  ah],
    ], dtype=np.float32)

    # ── Perspective transform ─────────────────────────────────────────────
    H, _ = cv2.findHomography(src_pts, dst_pts)
    warped = cv2.warpPerspective(ad_img, H, (frame.shape[1], frame.shape[0]))

    # ── Build mask for the bounding-box region ────────────────────────────
    mask = np.zeros(frame.shape[:2], dtype=np.uint8)
    cv2.fillConvexPoly(mask, dst_pts.astype(np.int32), 255)

    if edge_fade:
        # Slight gaussian blur on mask edges for soft compositing
        mask = cv2.GaussianBlur(mask, (9, 9), 0)

    # ── Alpha composite ───────────────────────────────────────────────────
    mask_f   = mask.astype(np.float32) / 255.0
    mask_3   = mask_f[:, :, np.newaxis]
    frame_f  = frame.astype(np.float32)
    warped_f = warped.astype(np.float32)

    composited = (
        warped_f  * mask_3 * blend_alpha +
        frame_f   * mask_3 * (1.0 - blend_alpha) +
        frame_f   * (1.0 - mask_3)
    )
    return np.clip(composited, 0, 255).astype(np.uint8)


# ── Draw Detection Info ───────────────────────────────────────────────────────
def draw_info_overlay(
    frame: np.ndarray,
    label: str,
    conf: float,
    x1: int, y1: int, x2: int, y2: int,
) -> np.ndarray:
    """Draw a small label badge above the bounding box."""
    tag   = f"{label} {conf:.2f}"
    font  = cv2.FONT_HERSHEY_SIMPLEX
    scale = 0.55
    thick = 1
    (tw, th), baseline = cv2.getTextSize(tag, font, scale, thick)

    # Badge background
    pad = 4
    by1 = max(0, y1 - th - 2 * pad)
    by2 = y1
    bx2 = min(frame.shape[1], x1 + tw + 2 * pad)
    cv2.rectangle(frame, (x1, by1), (bx2, by2), (0, 180, 80), -1)
    cv2.putText(frame, tag, (x1 + pad, y1 - pad), font, scale, (255, 255, 255), thick, cv2.LINE_AA)

    # Thin box outline around replaced region
    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 200, 90), 2)
    return frame


# ── Process Single Image ──────────────────────────────────────────────────────
def process_image(
    image_path: str | Path,
    model,
    ad_img: np.ndarray,
    blend_alpha: float = 0.88,
    save_dir: Path | None = None,
    show: bool = False,
) -> np.ndarray:
    image_path = Path(image_path)
    frame = cv2.imread(str(image_path))
    if frame is None:
        print(f"  ⚠️  Cannot read {image_path}")
        return None

    results = model(frame, verbose=False)[0]
    n_dets  = len(results.boxes)
    print(f"  📸 {image_path.name}: {n_dets} detection(s)")

    for box in results.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
        conf  = float(box.conf[0])
        cls   = int(box.cls[0])
        label = model.names[cls]

        frame = warp_ad_into_bbox(frame, ad_img, x1, y1, x2, y2, blend_alpha)
        frame = draw_info_overlay(frame, label, conf, x1, y1, x2, y2)

    if save_dir:
        out_path = save_dir / f"ad_{image_path.stem}.jpg"
        cv2.imwrite(str(out_path), frame)
        print(f"    💾 Saved → {out_path}")

    if show:
        try:
            from google.colab.patches import cv2_imshow
            cv2_imshow(frame)
        except ImportError:
            cv2.imshow("Ad Replaced", frame)
            cv2.waitKey(0)

    return frame


# ── Process Batch Folder ──────────────────────────────────────────────────────
def process_folder(
    folder: str | Path,
    model,
    ad_img: np.ndarray,
    blend_alpha: float = 0.88,
    save_dir: Path | None = None,
    extensions: tuple = (".jpg", ".jpeg", ".png", ".bmp", ".webp"),
):
    folder   = Path(folder)
    save_dir = save_dir or AD_OUTPUT_DIR / "images"
    save_dir.mkdir(parents=True, exist_ok=True)

    images = [p for p in folder.iterdir() if p.suffix.lower() in extensions]
    print(f"\n🗂️  Processing {len(images)} images from {folder}")
    for img_path in sorted(images):
        process_image(img_path, model, ad_img, blend_alpha, save_dir)
    print(f"\n✅ Batch complete. Results → {save_dir}")


# ── Process Video ─────────────────────────────────────────────────────────────
def process_video(
    video_path: str | Path,
    model,
    ad_img: np.ndarray,
    blend_alpha: float = 0.88,
    output_path: str | Path | None = None,
    max_frames: int | None = None,
    show_progress: bool = True,
):
    video_path  = Path(video_path)
    output_path = Path(output_path) if output_path else AD_OUTPUT_DIR / f"ad_{video_path.name}"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise IOError(f"Cannot open video: {video_path}")

    fps    = cap.get(cv2.CAP_PROP_FPS) or 25.0
    width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total  = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(output_path), fourcc, fps, (width, height))

    print(f"\n🎬 Processing video: {video_path.name}  ({width}×{height} @ {fps:.1f} fps)")
    print(f"   Total frames : {total}" + (f"  (capped at {max_frames})" if max_frames else ""))
    print(f"   Output       : {output_path}")

    frame_idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if max_frames and frame_idx >= max_frames:
            break

        results = model(frame, verbose=False)[0]
        for box in results.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
            conf  = float(box.conf[0])
            cls   = int(box.cls[0])
            label = model.names[cls]
            frame = warp_ad_into_bbox(frame, ad_img, x1, y1, x2, y2, blend_alpha)
            frame = draw_info_overlay(frame, label, conf, x1, y1, x2, y2)

        writer.write(frame)
        frame_idx += 1

        if show_progress and frame_idx % 30 == 0:
            pct = (frame_idx / total * 100) if total > 0 else 0
            print(f"   Frame {frame_idx}/{total}  ({pct:.1f}%)")

    cap.release()
    writer.release()
    print(f"\n✅ Video saved → {output_path}")
    return output_path


# ── Quick Test on Val / Test Images ───────────────────────────────────────────
def quick_test(model, ad_img: np.ndarray, n: int = 3):
    """Run ad replacement on up to `n` images from the dataset for a quick visual check."""
    test_dirs = [
        Path("datasets/billboard/images/test"),
        Path("datasets/billboard/images/val"),
        Path("datasets/billboard/images/train"),
    ]
    images = []
    for d in test_dirs:
        if d.exists():
            images.extend(list(d.glob("*.jpg")) + list(d.glob("*.png")))
        if len(images) >= n:
            break

    if not images:
        print("⚠️  No dataset images found for quick test. Pass your own image paths.")
        return

    save_dir = AD_OUTPUT_DIR / "quick_test"
    save_dir.mkdir(parents=True, exist_ok=True)
    print(f"\n🧪 Quick test: {min(n, len(images))} image(s)  →  {save_dir}")

    for img_path in images[:n]:
        process_image(img_path, model, ad_img, save_dir=save_dir, show=True)

    print("\n✅ Quick test done.")


# ── Colab Display Helper ───────────────────────────────────────────────────────
def show_results_grid(save_dir: Path, n: int = 6):
    """
    Show a grid of saved results in Colab using matplotlib.
    Call after process_folder() or quick_test().
    """
    import matplotlib.pyplot as plt
    import matplotlib.image as mpimg

    paths = sorted(save_dir.glob("*.jpg"))[:n]
    if not paths:
        print("No output images to display.")
        return

    cols = min(3, len(paths))
    rows = (len(paths) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(6 * cols, 4 * rows))
    axes = np.array(axes).flatten()

    for ax, p in zip(axes, paths):
        img = mpimg.imread(str(p))
        ax.imshow(img[..., ::-1])   # BGR → RGB
        ax.set_title(p.name, fontsize=8)
        ax.axis("off")

    for ax in axes[len(paths):]:
        ax.axis("off")

    plt.suptitle("Ad Replaced Results", fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.show()


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN — runs automatically when executed as a script / %run cell
# ══════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    print("=" * 60)
    print("  Part 4: Custom Ad Replacement")
    print("=" * 60)

    # 1. Load model
    model = load_model(conf_threshold=0.20)

    # 2. Load (or create placeholder) ad image
    #    ➡  Upload your own custom_ad.jpg to:
    #       /content/drive/MyDrive/billboard_project/custom_ad.jpg
    ad_img = load_or_create_ad(CUSTOM_AD_PATH)

    # 3. Quick test on dataset images
    quick_test(model, ad_img, n=3)

    # ── Uncomment below for more use-cases ────────────────────────────────

    # ── Process a single custom image ────────────────────────────────────
    # result = process_image(
    #     "/content/my_image.jpg",
    #     model, ad_img,
    #     blend_alpha=0.90,
    #     save_dir=AD_OUTPUT_DIR,
    #     show=True,
    # )

    # ── Process an entire folder ───────────────────────────────────────────
    # process_folder(
    #     folder   = "/content/my_images/",
    #     model    = model,
    #     ad_img   = ad_img,
    #     blend_alpha = 0.88,
    # )

    # ── Process a video ────────────────────────────────────────────────────
    # process_video(
    #     video_path  = "/content/drive/MyDrive/billboard_project/test_video.mp4",
    #     model       = model,
    #     ad_img      = ad_img,
    #     blend_alpha = 0.88,
    #     max_frames  = 300,   # remove to process entire video
    # )

    # 4. Show a grid of results
    show_results_grid(AD_OUTPUT_DIR / "quick_test")

    print("\n🎉 Part 4 complete!")
    print(f"   All outputs → {AD_OUTPUT_DIR}")
    print()
    print("Next steps:")
    print("  • Upload your real ad image to Drive as custom_ad.jpg")
    print("  • Call process_video() on your test footage")
    print("  • Tune blend_alpha (0.7–1.0) for realism")
    print("  • Part 5: perspective-quad detection for non-rectangular billboards")

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║         Part 4 — Upload & Replace  (paste as ONE cell)       ║
# ║         v2: billboard-only + auto conf/blend                 ║
# ╚══════════════════════════════════════════════════════════════╝

import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# ── Make sure part4 functions are available ──────────────────────────────────
try:
    _ = warp_ad_into_bbox
except NameError:
#     %run /content/drive/MyDrive/billboard_project/part4_ad_replacement.py   # noqa

# ── State ─────────────────────────────────────────────────────────────────────
state = {"ad_img": None, "target_imgs": {}}

# ═════════════════════════════════════════════════════════════════════════════
# Helpers
# ═════════════════════════════════════════════════════════════════════════════
def bytes_to_bgr(raw):
    arr = np.frombuffer(raw, np.uint8)
    return cv2.imdecode(arr, cv2.IMREAD_COLOR)

def bgr_to_rgb(img):
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

def show_comparison(orig, replaced, title=""):
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    axes[0].imshow(bgr_to_rgb(orig));     axes[0].set_title("Original",     fontsize=13, fontweight="bold"); axes[0].axis("off")
    axes[1].imshow(bgr_to_rgb(replaced)); axes[1].set_title("Ad Replaced",  fontsize=13, fontweight="bold", color="#1a7a3c"); axes[1].axis("off")
    if title: fig.suptitle(title, fontsize=10, color="#555")
    plt.tight_layout(); plt.show()

# ─── Auto-tune: pick conf & blend per image ───────────────────────────────────
def auto_tune(image: np.ndarray, model):
    """
    Run inference at low conf, then pick:
      • conf_threshold  — just below the highest-confidence billboard score
                          so we keep real billboards but drop noise
      • blend_alpha     — brighter/higher-contrast scenes get higher alpha
    Returns (conf_used, alpha_used, filtered_boxes)
    where filtered_boxes = list of (x1,y1,x2,y2, conf_val, label) for 'billboard' only
    """
    # ── 1. Run at very low conf to see all possible detections ────────────────
    model.conf = 0.05
    results = model(image, verbose=False)[0]

    billboard_scores = []
    for box in results.boxes:
        cls   = int(box.cls[0])
        label = model.names[cls]
        if label == "billboard":
            billboard_scores.append(float(box.conf[0]))

    # ── 2. Decide confidence threshold ────────────────────────────────────────
    if not billboard_scores:
        # No billboards found even at 0.05 — use a loose threshold anyway
        conf_threshold = 0.10
    elif len(billboard_scores) == 1:
        # Only one billboard: accept it if score > 0.20, else lower to capture it
        conf_threshold = max(0.10, billboard_scores[0] - 0.05)
    else:
        # Multiple billboards: set threshold just below the median score
        # so we keep genuine ones and skip borderline noise
        billboard_scores.sort(reverse=True)
        median_score   = billboard_scores[len(billboard_scores) // 2]
        conf_threshold = max(0.10, median_score - 0.08)

    # ── 3. Collect final billboard boxes above threshold ──────────────────────
    final_boxes = []
    for box in results.boxes:
        cls      = int(box.cls[0])
        label    = model.names[cls]
        conf_val = float(box.conf[0])
        if label == "billboard" and conf_val >= conf_threshold:
            x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
            final_boxes.append((x1, y1, x2, y2, conf_val, label))

    # ── 4. Auto blend alpha: based on image brightness variance ──────────────
    # High-contrast outdoor scenes → higher alpha (ad stands out)
    # Low-light / indoor → slightly lower alpha (blend in)
    gray      = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    std_dev   = float(np.std(gray))          # 0–128 typical range
    alpha     = np.clip(0.78 + (std_dev / 128) * 0.18, 0.78, 0.96)

    return round(conf_threshold, 2), round(alpha, 2), final_boxes


# ═════════════════════════════════════════════════════════════════════════════
# STEP 1 — Upload Ad Image
# ═════════════════════════════════════════════════════════════════════════════
display(HTML("""
<div style='background:#1e3a5f;color:white;padding:12px 18px;border-radius:8px;
            font-family:monospace;font-size:14px;margin-bottom:6px'>
  <b>STEP 1 :</b> Upload your Advertisement / Logo image (jpg, png)
</div>"""))

btn_ad  = widgets.Button(description="📤 Upload Ad Image", button_style="primary",
                         layout=widgets.Layout(width="220px", height="38px"))
out_ad  = widgets.Output()

def on_upload_ad(_):
    with out_ad:
        clear_output()
        print("Opening file picker …")
        uploaded = files.upload()
        if not uploaded: print("⚠️  No file selected."); return
        fname, raw = next(iter(uploaded.items()))
        img = bytes_to_bgr(raw)
        if img is None: print(f"❌ Could not decode {fname}"); return
        state["ad_img"] = img
        print(f"✅ Ad loaded: {fname}  ({img.shape[1]}×{img.shape[0]} px)")
        plt.figure(figsize=(5, 3)); plt.imshow(bgr_to_rgb(img))
        plt.title("Your Ad Image", fontweight="bold"); plt.axis("off"); plt.tight_layout(); plt.show()

btn_ad.on_click(on_upload_ad)
display(widgets.VBox([btn_ad, out_ad]))

# ═════════════════════════════════════════════════════════════════════════════
# STEP 2 — Upload Target Image(s)
# ═════════════════════════════════════════════════════════════════════════════
display(HTML("""
<div style='background:#2d5a1b;color:white;padding:12px 18px;border-radius:8px;
            font-family:monospace;font-size:14px;margin:12px 0 6px'>
  <b>STEP 2 :</b> Upload Target Image(s) where billboards should be replaced
  <br><small style='opacity:.8'>Multi-select supported. Only <b>billboard</b> class will be replaced — signage is ignored.</small>
</div>"""))

btn_target  = widgets.Button(description="📤 Upload Target Image(s)", button_style="success",
                             layout=widgets.Layout(width="260px", height="38px"))
out_target  = widgets.Output()

def on_upload_target(_):
    with out_target:
        clear_output()
        print("Opening file picker …")
        uploaded = files.upload()
        if not uploaded: print("⚠️  No files selected."); return
        state["target_imgs"] = {}
        for fname, raw in uploaded.items():
            img = bytes_to_bgr(raw)
            if img is not None:
                state["target_imgs"][fname] = img
                print(f"  ✅ {fname}  ({img.shape[1]}×{img.shape[0]})")
            else:
                print(f"  ❌ Could not decode {fname}")
        print(f"\n📂 {len(state['target_imgs'])} target image(s) ready.")

btn_target.on_click(on_upload_target)
display(widgets.VBox([btn_target, out_target]))

# ═════════════════════════════════════════════════════════════════════════════
# STEP 3 — Run (fully automatic)
# ═════════════════════════════════════════════════════════════════════════════
display(HTML("""
<div style='background:#4a1f6e;color:white;padding:12px 18px;border-radius:8px;
            font-family:monospace;font-size:14px;margin:12px 0 6px'>
  <b>STEP 3 :</b> Run — confidence threshold &amp; blend are set <b>automatically per image</b>
  <br><small style='opacity:.8'>Only <b>billboard</b> detections are replaced. Signage, branding = skipped.</small>
</div>"""))

chk_save = widgets.Checkbox(value=True, description="Save outputs to Drive", indent=False)
display(chk_save)

btn_run = widgets.Button(description="🚀 Run Ad Replacement", button_style="danger",
                         layout=widgets.Layout(width="250px", height="42px", margin="10px 0 0 0"))
out_run = widgets.Output()

def on_run(_):
    with out_run:
        clear_output()

        if state["ad_img"] is None:
            print("❌ Please upload an Ad Image first (Step 1)."); return
        if not state["target_imgs"]:
            print("❌ Please upload at least one Target Image (Step 2)."); return

        from ultralytics import YOLO
        _model_path = find_model()
        _model = YOLO(str(_model_path))
        print("✅ Model loaded\n")

        ad_img   = state["ad_img"]
        save_dir = AD_OUTPUT_DIR / "cell_output"
        if chk_save.value:
            save_dir.mkdir(parents=True, exist_ok=True)

        for fname, orig in state["target_imgs"].items():
            print(f"── Processing: {fname}")

            # ── Auto-tune per image ──────────────────────────────────────────
            conf_thr, alpha, final_boxes = auto_tune(orig, _model)
            print(f"   🔧 Auto-settings → conf ≥ {conf_thr}  |  blend α = {alpha}")
            print(f"   🎯 Billboard detections: {len(final_boxes)}")

            replaced = orig.copy()

            if not final_boxes:
                print("   ⚠️  No billboard detected — image shown as-is.")
            else:
                for (x1, y1, x2, y2, conf_val, label) in final_boxes:
                    area = (x2 - x1) * (y2 - y1)
                    print(f"      • {label} ({conf_val:.2f})  box=[{x1},{y1},{x2},{y2}]  area={area}px²")
                    replaced = warp_ad_into_bbox(replaced, ad_img, x1, y1, x2, y2, alpha)
                    replaced = draw_info_overlay(replaced, label, conf_val, x1, y1, x2, y2)

            n = len(final_boxes)
            show_comparison(orig, replaced, title=f"{fname}  |  {n} billboard(s) replaced")

            if chk_save.value:
                stem     = Path(fname).stem
                out_path = save_dir / f"replaced_{stem}.jpg"
                cv2.imwrite(str(out_path), replaced)
                print(f"   💾 Saved → {out_path}")
            print()

        if chk_save.value:
            print(f"✅ All outputs saved → {save_dir}")
        print("🎉 Done!")

btn_run.on_click(on_run)
display(widgets.VBox([btn_run, out_run]))

"""
Part 5: Perspective-Correct Ad Replacement (Quad Detection + True Homography)
==============================================================================
Run AFTER Part 4.

What this adds over Part 4:
  • Detects the actual 4 corners of each billboard (not just axis-aligned bbox)
  • Uses those corners as the homography destination → ad is perspective-correct
  • Corners found via: Canny edges → contour approx → quad fitting inside bbox
  • Fallback: if no clean quad found, uses the bbox corners (same as Part 4)
  • Paste as a NEW Colab cell — uploads ad + target images interactively

Visual difference:
  Part 4 → ad placed in a rectangle (looks overlaid)
  Part 5 → ad follows the actual tilted/rotated plane (looks painted on)
"""

# ── Imports ───────────────────────────────────────────────────────────────────
import cv2
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
from google.colab import files, drive
from pathlib import Path

# ── Drive ─────────────────────────────────────────────────────────────────────
try:
    drive.mount("/content/drive", force_remount=False)
except Exception:
    pass

DRIVE_ROOT    = Path("/content/drive/MyDrive/billboard_project")
OUTPUT_DIR    = DRIVE_ROOT / "part5_perspective_output"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# 1. MODEL LOADER
# ─────────────────────────────────────────────────────────────────────────────
def find_model():
    import glob
    for p in [
        DRIVE_ROOT / "best.pt",
        *[Path(x) for x in glob.glob(str(DRIVE_ROOT / "**" / "best.pt"), recursive=True)],
        Path("runs/detect/train/weights/best.pt"),
    ]:
        if p.exists():
            return p
    raise FileNotFoundError("❌ best.pt not found. Run Part 2 first.")

def load_yolo(conf=0.05):
    from ultralytics import YOLO
    m = YOLO(str(find_model()))
    m.conf = conf
    return m

# ─────────────────────────────────────────────────────────────────────────────
# 2. QUAD DETECTION — find 4 actual corners inside a bounding box
# ─────────────────────────────────────────────────────────────────────────────
def order_corners(pts: np.ndarray) -> np.ndarray:
    """
    Order 4 points as: top-left, top-right, bottom-right, bottom-left.
    Works for any quadrilateral (tilted, perspective-distorted, etc.)
    """
    pts  = pts.reshape(4, 2).astype(np.float32)
    rect = np.zeros((4, 2), dtype=np.float32)
    s    = pts.sum(axis=1)
    diff = np.diff(pts, axis=1).ravel()
    rect[0] = pts[np.argmin(s)]      # top-left     (min x+y)
    rect[2] = pts[np.argmax(s)]      # bottom-right (max x+y)
    rect[1] = pts[np.argmin(diff)]   # top-right    (min x-y)
    rect[3] = pts[np.argmax(diff)]   # bottom-left  (max x-y)
    return rect


def detect_quad_in_roi(
    image: np.ndarray,
    x1: int, y1: int, x2: int, y2: int,
    debug: bool = False,
) -> np.ndarray:
    """
    Try to find a 4-corner quadrilateral inside the bounding box [x1,y1,x2,y2].

    Strategy:
      1. Crop the ROI with a small margin
      2. Blur → Canny edges
      3. Find external contours → pick largest area quadrilateral
      4. If no good quad, fall back to the bbox corners themselves

    Returns ordered (4,2) float32 array in FULL IMAGE coordinates.
    """
    pad   = 6
    rx1   = max(0, x1 - pad)
    ry1   = max(0, y1 - pad)
    rx2   = min(image.shape[1], x2 + pad)
    ry2   = min(image.shape[0], y2 + pad)
    roi   = image[ry1:ry2, rx1:rx2]

    if roi.size == 0:
        return _bbox_corners(x1, y1, x2, y2)

    gray  = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    blur  = cv2.GaussianBlur(gray, (5, 5), 0)

    # ── Adaptive Canny thresholds ─────────────────────────────────────────────
    med         = float(np.median(blur))
    low, high   = max(0, 0.5 * med), min(255, 1.5 * med)
    edges       = cv2.Canny(blur, low, high)
    edges       = cv2.dilate(edges, np.ones((3, 3), np.uint8), iterations=1)

    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return _bbox_corners(x1, y1, x2, y2)

    roi_area    = (rx2 - rx1) * (ry2 - ry1)
    best_quad   = None
    best_area   = 0

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area < roi_area * 0.10:          # skip tiny noise contours
            continue
        peri  = cv2.arcLength(cnt, True)
        approx = cv2.approxPolyDP(cnt, 0.04 * peri, True)
        if len(approx) == 4 and area > best_area:
            best_area = area
            best_quad = approx

    if best_quad is None:
        # No 4-sided contour — try largest contour's convex hull → bbox
        largest = max(contours, key=cv2.contourArea)
        hull    = cv2.convexHull(largest)
        peri    = cv2.arcLength(hull, True)
        approx  = cv2.approxPolyDP(hull, 0.04 * peri, True)
        if len(approx) == 4:
            best_quad = approx
        else:
            return _bbox_corners(x1, y1, x2, y2)

    # ── Convert ROI-local coords → full image coords ──────────────────────────
    pts_full = best_quad.reshape(4, 2).astype(np.float32)
    pts_full[:, 0] += rx1
    pts_full[:, 1] += ry1

    # ── Sanity check: quad must be mostly inside the bbox ─────────────────────
    cx = pts_full[:, 0].mean()
    cy = pts_full[:, 1].mean()
    if not (x1 <= cx <= x2 and y1 <= cy <= y2):
        return _bbox_corners(x1, y1, x2, y2)

    return order_corners(pts_full)


def _bbox_corners(x1, y1, x2, y2) -> np.ndarray:
    """Fallback: axis-aligned bounding box corners (same as Part 4)."""
    return np.array([
        [x1, y1], [x2, y1],
        [x2, y2], [x1, y2],
    ], dtype=np.float32)


# ─────────────────────────────────────────────────────────────────────────────
# 3. PERSPECTIVE WARP + COMPOSITE
# ─────────────────────────────────────────────────────────────────────────────
def warp_ad_perspective(
    frame: np.ndarray,
    ad_img: np.ndarray,
    dst_corners: np.ndarray,       # ordered (4,2) in image coords
    blend_alpha: float = 0.92,
    edge_fade: bool = True,
) -> np.ndarray:
    """
    Warp ad_img so its 4 corners map to dst_corners on frame.
    Uses full perspective homography — handles tilt, rotation, foreshortening.
    """
    frame   = frame.copy()
    ah, aw  = ad_img.shape[:2]

    src_pts = np.array([
        [0,  0 ], [aw, 0 ],
        [aw, ah], [0,  ah],
    ], dtype=np.float32)

    H, _    = cv2.findHomography(src_pts, dst_corners)
    if H is None:
        return frame

    warped  = cv2.warpPerspective(ad_img, H, (frame.shape[1], frame.shape[0]))

    # ── Mask for the destination quadrilateral ────────────────────────────────
    mask    = np.zeros(frame.shape[:2], dtype=np.uint8)
    cv2.fillConvexPoly(mask, dst_corners.astype(np.int32), 255)

    if edge_fade:
        mask = cv2.GaussianBlur(mask, (11, 11), 0)

    mask_f   = mask.astype(np.float32) / 255.0
    mask_3   = mask_f[:, :, np.newaxis]
    result   = (
        warped.astype(np.float32)  * mask_3 * blend_alpha +
        frame.astype(np.float32)   * mask_3 * (1.0 - blend_alpha) +
        frame.astype(np.float32)   * (1.0 - mask_3)
    )
    return np.clip(result, 0, 255).astype(np.uint8)


def draw_quad_overlay(
    frame: np.ndarray,
    corners: np.ndarray,
    label: str,
    conf: float,
    used_quad: bool,
) -> np.ndarray:
    """Draw the detected quad outline + label badge."""
    pts   = corners.astype(np.int32).reshape((-1, 1, 2))
    color = (0, 220, 100) if used_quad else (0, 160, 255)   # green=quad, orange=bbox fallback
    cv2.polylines(frame, [pts], isClosed=True, color=color, thickness=2)

    tag   = f"{label} {conf:.2f} {'[QUAD]' if used_quad else '[BBOX]'}"
    tl    = tuple(corners[0].astype(int))
    cv2.putText(frame, tag, (tl[0], max(0, tl[1] - 8)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 1, cv2.LINE_AA)
    return frame


# ─────────────────────────────────────────────────────────────────────────────
# 4. AUTO-TUNE (billboard-only, same logic as Part 4 cell)
# ─────────────────────────────────────────────────────────────────────────────
def auto_tune(image, model):
    model.conf = 0.05
    results    = model(image, verbose=False)[0]
    scores     = [float(b.conf[0]) for b in results.boxes
                  if model.names[int(b.cls[0])] == "billboard"]

    if not scores:
        conf_thr = 0.10
    elif len(scores) == 1:
        conf_thr = max(0.10, scores[0] - 0.05)
    else:
        scores.sort(reverse=True)
        conf_thr = max(0.10, scores[len(scores)//2] - 0.08)

    final = []
    for b in results.boxes:
        lbl  = model.names[int(b.cls[0])]
        conf = float(b.conf[0])
        if lbl == "billboard" and conf >= conf_thr:
            x1, y1, x2, y2 = map(int, b.xyxy[0].tolist())
            final.append((x1, y1, x2, y2, conf, lbl))

    gray  = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    alpha = float(np.clip(0.80 + (np.std(gray) / 128) * 0.16, 0.80, 0.96))
    return round(conf_thr, 2), round(alpha, 2), final


# ─────────────────────────────────────────────────────────────────────────────
# 5. FULL PIPELINE — process one image
# ─────────────────────────────────────────────────────────────────────────────
def process_image_p5(image, ad_img, model, debug=False):
    """
    Returns (replaced_frame, report_lines, n_quad, n_bbox_fallback)
    """
    conf_thr, alpha, boxes = auto_tune(image, model)
    report = [f"Auto-settings → conf ≥ {conf_thr}  |  blend α = {alpha:.2f}  |  {len(boxes)} billboard(s)"]

    replaced      = image.copy()
    n_quad        = 0
    n_bbox_fb     = 0

    for (x1, y1, x2, y2, conf_val, label) in boxes:
        # ── Try quad detection ────────────────────────────────────────────────
        corners   = detect_quad_in_roi(image, x1, y1, x2, y2, debug)
        bbox_corn = _bbox_corners(x1, y1, x2, y2)

        # Determine if we got a real quad or fell back
        used_quad = not np.allclose(corners, bbox_corn, atol=2.0)
        if used_quad:
            n_quad   += 1
            mode_str  = "QUAD (perspective)"
        else:
            n_bbox_fb += 1
            mode_str  = "BBOX fallback"

        area = (x2 - x1) * (y2 - y1)
        report.append(f"  • {label} ({conf_val:.2f})  {mode_str}  area={area}px²")
        report.append(f"    corners: {corners.astype(int).tolist()}")

        replaced = warp_ad_perspective(replaced, ad_img, corners, alpha)
        replaced = draw_quad_overlay(replaced, corners, label, conf_val, used_quad)

    return replaced, report, n_quad, n_bbox_fb


# ─────────────────────────────────────────────────────────────────────────────
# 6. INTERACTIVE COLAB CELL UI
# ─────────────────────────────────────────────────────────────────────────────
state = {"ad_img": None, "target_imgs": {}}

def bytes_to_bgr(raw):
    return cv2.imdecode(np.frombuffer(raw, np.uint8), cv2.IMREAD_COLOR)

def show_comparison(orig, replaced, title="", report_lines=None):
    fig, axes = plt.subplots(1, 2, figsize=(17, 6))
    axes[0].imshow(cv2.cvtColor(orig,     cv2.COLOR_BGR2RGB))
    axes[0].set_title("Original",    fontsize=13, fontweight="bold"); axes[0].axis("off")
    axes[1].imshow(cv2.cvtColor(replaced, cv2.COLOR_BGR2RGB))
    axes[1].set_title("Part 5 — Perspective Warp", fontsize=13, fontweight="bold", color="#1a5c3a")
    axes[1].axis("off")
    if title: fig.suptitle(title, fontsize=10, color="#444")
    plt.tight_layout(); plt.show()
    if report_lines:
        for line in report_lines:
            print("  " + line)

# ── STEP 1: Upload Ad ─────────────────────────────────────────────────────────
display(HTML("""
<div style='background:#1e3a5f;color:white;padding:12px 18px;border-radius:8px;
            font-family:monospace;font-size:14px;margin-bottom:6px'>
  <b>PART 5 — STEP 1 :</b> Upload your Advertisement / Logo image (jpg, png)
</div>"""))

btn_ad, out_ad = widgets.Button(description="📤 Upload Ad Image", button_style="primary",
    layout=widgets.Layout(width="220px", height="38px")), widgets.Output()

def on_ad(_):
    with out_ad:
        clear_output()
        up = files.upload()
        if not up: print("⚠️  Nothing selected."); return
        fname, raw = next(iter(up.items()))
        img = bytes_to_bgr(raw)
        if img is None: print(f"❌ Cannot decode {fname}"); return
        state["ad_img"] = img
        print(f"✅ Ad loaded: {fname}  ({img.shape[1]}×{img.shape[0]})")
        plt.figure(figsize=(5,3)); plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        plt.title("Ad Image"); plt.axis("off"); plt.tight_layout(); plt.show()

btn_ad.on_click(on_ad)
display(widgets.VBox([btn_ad, out_ad]))

# ── STEP 2: Upload Target Images ──────────────────────────────────────────────
display(HTML("""
<div style='background:#2d5a1b;color:white;padding:12px 18px;border-radius:8px;
            font-family:monospace;font-size:14px;margin:12px 0 6px'>
  <b>PART 5 — STEP 2 :</b> Upload Target Image(s) with billboards
  <br><small style='opacity:.8'>
    Green outline = quad detected (perspective-correct) &nbsp;|&nbsp;
    Orange outline = bbox fallback (same as Part 4)
  </small>
</div>"""))

btn_tgt, out_tgt = widgets.Button(description="📤 Upload Target Image(s)", button_style="success",
    layout=widgets.Layout(width="260px", height="38px")), widgets.Output()

def on_tgt(_):
    with out_tgt:
        clear_output()
        up = files.upload()
        if not up: print("⚠️  Nothing selected."); return
        state["target_imgs"] = {}
        for fname, raw in up.items():
            img = bytes_to_bgr(raw)
            if img is not None:
                state["target_imgs"][fname] = img
                print(f"  ✅ {fname}  ({img.shape[1]}×{img.shape[0]})")
        print(f"\n📂 {len(state['target_imgs'])} image(s) ready.")

btn_tgt.on_click(on_tgt)
display(widgets.VBox([btn_tgt, out_tgt]))

# ── STEP 3: Run ───────────────────────────────────────────────────────────────
display(HTML("""
<div style='background:#4a1f6e;color:white;padding:12px 18px;border-radius:8px;
            font-family:monospace;font-size:14px;margin:12px 0 6px'>
  <b>PART 5 — STEP 3 :</b> Run perspective-correct replacement
  <br><small style='opacity:.8'>
    Conf threshold &amp; blend alpha are auto-tuned per image.
    Only <b>billboard</b> class is replaced.
  </small>
</div>"""))

chk_save = widgets.Checkbox(value=True, description="Save outputs to Drive", indent=False)
display(chk_save)

btn_run, out_run = widgets.Button(description="🚀 Run Part 5", button_style="danger",
    layout=widgets.Layout(width="220px", height="42px", margin="10px 0 0 0")), widgets.Output()

def on_run(_):
    with out_run:
        clear_output()
        if state["ad_img"] is None:   print("❌ Upload Ad Image first (Step 1)."); return
        if not state["target_imgs"]:  print("❌ Upload Target Image(s) first (Step 2)."); return

        model = load_yolo()
        print(f"✅ Model loaded → {find_model().name}\n")

        for fname, orig in state["target_imgs"].items():
            print(f"━━ {fname}")
            replaced, report, nq, nb = process_image_p5(orig, state["ad_img"], model)
            title = (f"{fname}  |  {nq} quad-detected  +  {nb} bbox-fallback")
            show_comparison(orig, replaced, title=title, report_lines=report)

            if chk_save.value:
                out_path = OUTPUT_DIR / f"p5_{Path(fname).stem}.jpg"
                cv2.imwrite(str(out_path), replaced)
                print(f"  💾 Saved → {out_path}")
            print()

        if chk_save.value:
            print(f"✅ All outputs → {OUTPUT_DIR}")
        print("\n🎉 Part 5 complete!")
        print("\nLegend:")
        print("  🟢 Green outline  = perspective quad detected (ad follows actual billboard plane)")
        print("  🟠 Orange outline = bbox fallback (no clean quad found — same as Part 4)")
        print("\nIf you see mostly orange, it means the billboard surface has low edge contrast.")
        print("→ Collecting more varied training data (Priority 1) will help the model give")
        print("  tighter boxes, which gives the quad detector better input to work with.")

btn_run.on_click(on_run)
display(widgets.VBox([btn_run, out_run]))

# ── Quick Evaluation — no external file needed ────────────────────────────
import glob
from pathlib import Path
from ultralytics import YOLO

DRIVE_ROOT = Path("/content/drive/MyDrive/billboard_project")

# Find model
candidates = [DRIVE_ROOT / "best.pt",
              *[Path(p) for p in glob.glob(str(DRIVE_ROOT / "**" / "best.pt"), recursive=True)]]
model_path = next(p for p in candidates if p.exists())
print(f"✅ Model: {model_path}")

# Find data.yaml
yaml_candidates = [
    Path("datasets/billboard/data.yaml"),
    DRIVE_ROOT / "data.yaml",
    *[Path(p) for p in glob.glob(str(DRIVE_ROOT / "**" / "data.yaml"), recursive=True)],
]
yaml_path = next(p for p in yaml_candidates if p.exists())
print(f"✅ data.yaml: {yaml_path}\n")

# Run validation
model   = YOLO(str(model_path))
metrics = model.val(data=str(yaml_path), split="test", verbose=True)

print("\n" + "="*45)
print("  EVALUATION RESULTS")
print("="*45)
print(f"  mAP@0.5      : {metrics.box.map50:.4f}")
print(f"  mAP@0.5:0.95 : {metrics.box.map:.4f}")
print(f"  Precision    : {metrics.box.mp:.4f}")
print(f"  Recall       : {metrics.box.mr:.4f}")
print("="*45)
print("\nPaste these numbers in chat → I'll tell you if you need more data.")

